Ecommercesite/Ecommercesite/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path("shop/",include("products.urls" , namespace = "products")),
    path("cart/",include("cart.urls")),
    path("orders/",include("orders.urls"))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Ecommercesite/cart/urls.py
from django.urls import path
from . import views


app_name= 'cart'

urlpatterns = [
    path('add/<int:product_id>/',views.cart_add , name="cart_add"),
    path("",views.cart_detail , name="cart_detail"),
    path("remove/<int:product_id>/", views.cart_remove, name="remove_item")
]

Ecommercesite/products/urls.py
from django.urls import path
from . import views

app_name = "products"

urlpatterns = [
    path('chatbot/', views.chatbot_view, name='chatbot'),
    path('', views.product_list, name='product_list'),
    path('<slug:cat_slug>/', views.product_list, name='product_list_by_category'),
    path('product/<int:id>/<slug:slug>/', views.product_detail, name="product_detail"),
]

Ecommercesite/templates/includes/nav.html
<nav class="container mx-auto p-4 flex justify-between items-center">
    <a href="{% url 'products:product_list' %}" class="text-2xl font-bold text-indigo-600">E-Com</a>

<a href="{% url 'cart:cart_detail' %}">
    <svg class="w-8" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 width="40px" height="36px" viewBox="0 0 40 36" style="enable-background:new 0 0 40 36;" xml:space="preserve">
<g id="Page-1_4_" sketch:type="MSPage">
	<g id="Desktop_4_" transform="translate(-84.000000, -410.000000)" sketch:type="MSArtboardGroup">
		<path id="Cart" sketch:type="MSShapeGroup" class="st0" d="M94.5,434.6h24.8l4.7-15.7H92.2l-1.3-8.9H84v4.8h3.1l3.7,27.8h0.1
			c0,1.9,1.8,3.4,3.9,3.4c2.2,0,3.9-1.5,3.9-3.4h12.8c0,1.9,1.8,3.4,3.9,3.4c2.2,0,3.9-1.5,3.9-3.4h1.7v-3.9l-25.8-0.1L94.5,434.6"
			/>
	</g>
</g>
  </svg>
</a>
</nav>