Ecommercesite/Ecommercesite/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path("shop/",include("products.urls" , namespace = "products")),
    path("cart/",include("cart.urls")),
    path("orders/",include("orders.urls"))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Ecommercesite/cart/urls.py
from django.urls import path
from . import views


app_name= 'cart'

urlpatterns = [
    path('add/<int:product_id>/',views.cart_add , name="cart_add"),
    path("",views.cart_detail , name="cart_detail"),
    path("remove/<int:product_id>/", views.cart_remove, name="remove_item")
]

Ecommercesite/orders/urls.py
from django.urls import path
from . import views

app_name= 'orders'

urlpatterns = [
    path('create',views.order_create , name="order_create"),
    path("confirmation/<int:order_id>",views.order_confirmation , name="order_confirmation"),
]

Ecommercesite/products/urls.py
from django.urls import path
from . import views

app_name = "products"

urlpatterns = [
    path('chatbot/', views.chatbot_view, name='chatbot'),
    path('', views.product_list, name='product_list'),
    path('<slug:cat_slug>/', views.product_list, name='product_list_by_category'),
    path('product/<int:id>/<slug:slug>/', views.product_detail, name="product_detail"),
]

Ecommercesite/cart/models.py
from django.db import models
from products.models import Product
# Create your models here.
class Cart(models.Model):
    created_at=models.DateTimeField(auto_now_add=True)
    def get_total_price(self):
        return sum(item.get_total_price() for item in self.items.all()) 



class CartItem(models.Model):
    cart = models.ForeignKey(Cart,related_name="items",on_delete=models.CASCADE)
    product = models.ForeignKey(Product,related_name="cart_items",on_delete=models.CASCADE)
    quantity= models.PositiveIntegerField(default=1)
    def get_total_price(self):
        return self.product.price * self.quantity

Ecommercesite/cart/views.py
from django.shortcuts import render , get_object_or_404 ,redirect
from products.models import Product
from .models  import Cart , CartItem
from django.views.decorators.http import require_POST
from django.http import JsonResponse
# Create your views here.


@require_POST
def cart_add(request,product_id):
    cart_id = request.session.get('cart_id')
    if cart_id:
        try:
            cart = Cart.objects.get(id = cart_id)
        except Cart.DoesNotExist:
            cart =  Cart.objects.create()
    else:
        cart =  Cart.objects.create()
        request.session['cart_id'] = cart.id
    product= get_object_or_404(Product , id = product_id)
    cart_item , created = CartItem.objects.get_or_create(cart = cart ,product = product)
    if not created:
        cart_item.quantity +=1
    cart_item.save()
    response_data = {
        "success":True ,
        "message":f'added {product.name} to cart'
    }
    return JsonResponse(response_data)
def cart_detail(request):
    cart_id = request.session.get('cart_id')
    cart = None
    if  cart_id:
        cart = get_object_or_404(Cart,id = cart_id)
    if not cart or not cart.items.exists():
        cart = None
    return render(request ,"cart/detail.html",{"cart":cart})
def cart_remove(request, product_id):
    cart_id = request.session.get('cart_id')
    cart = get_object_or_404(Cart, id=cart_id)
    item = get_object_or_404(CartItem, id=product_id, cart=cart)
    item.delete()
    
    return redirect("cart:cart_detail")

Ecommercesite/cart/templates/cart/detail.html
{% extends "base.html" %}
{%block title%} My Cart {%endblock%}

{%block content%}
{%if cart %}
<ul class="space-y-4">
    {%for item in cart.items.all %}
    <li class="flex items-center p-4">
        {%if item.product.image%}
        <img src="{{item.product.image.url}}" alt={{item.product.name}} class="w-24 mr-4">
        {%endif%}
        <div class="flex-grow">
            <a href="{%url 'products:product_detail' item.product.id item.product.slug%}">
        <h3 class="font-semibold text-lg">{{item.product.name}}</h3>
            </a>
        <p class="text-gray-700">{{item.product.description}}</p>
        <p class="text-indigo-600">${{item.product.price}}</p>
        <p class="text-gray-600">Quantity: {{item.quantity}}</p>
        <div class="flex-shrink">
            <form action="{% url 'cart:remove_item' item.id %}" method="post">
                {% csrf_token %}
                <button type="submit" 
                style="background-color: #dc2626; color: white; font-weight: bold; padding: 8px 12px; border-radius: 4px; border: none; box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1); cursor: pointer; transition: all 0.03s ease-in-out;"
                onmouseover="this.style.borderRadius='9999px'; this.style.backgroundColor='#b91c1c'" 
                onmouseout="this.style.borderRadius='4px'; this.style.backgroundColor='#dc2626'">
                ✖
            </button>
            
            </form>
        </div>
    </li>
    {%endfor%}
{%else%}
<P>Cart is empty</P>
{%endif%}
{%if cart.get_total_price %}
<p><strong>Total price :{{cart.get_total_price}}$</p>
{%endif%}
{%if cart%}

<form action="{% url 'orders:order_create'%}" method="post">
    {%csrf_token%}
    <button type="submit" 
    style="width: 100%; background-color: #4f46e5; color: white; font-weight: 500; padding: 5px 14px; 
    border-radius: 8px; box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1); border: none; 
    cursor: pointer; transition: background-color 0.3s ease-in-out, transform 0.2s ease-in-out;"
    onmouseover="this.style.backgroundColor='#4338ca'; this.style.transform='scale(1.05)'" 
    onmouseout="this.style.backgroundColor='#4f46e5'; this.style.transform='scale(1)'">
    Proceed to Checkout
    </button>

</form>
{%endif%}

</ul>

{%endblock%}